services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      DATABASE_HOSTNAME: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: Theta$999
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: e7c90f2ceb97fd95c8cd84ece59521fa46f8c954bf10236d2bc45a6ef75f83cf
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Theta$999
      POSTGRES_DB: fastapi
    volumes:
      - postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fastapi"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-db:
