"""add courses, course_contents, tests

Revision ID: ed0ea491a939
Revises: e29dbe021ca6
Create Date: 2025-09-08 23:53:59.217588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0ea491a939'
down_revision: Union[str, Sequence[str], None] = 'e29dbe021ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('course_desc', sa.String(), nullable=True),
    sa.Column('course_img', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_id'), 'tests', ['id'], unique=False)
    op.create_index(op.f('ix_tests_test_name'), 'tests', ['test_name'], unique=False)
    op.create_table('course_batch',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE')
    )
    op.create_table('course_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('youtube_link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_contents_id'), 'course_contents', ['id'], unique=False)
    op.create_table('course_faculty',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE')
    )
    op.create_table('course_student',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE')
    )
    op.create_table('course_subject',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE')
    )
    op.create_table('test_faculty',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE')
    )
    op.create_table('test_student',
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE')
    )
    op.drop_column('batch_faculties', 'id')
    op.drop_column('batch_students', 'id')
    op.alter_column('batches', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('batches', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('batches', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.create_index(op.f('ix_batches_name'), 'batches', ['name'], unique=False)
    op.drop_column('batches', 'num_learners')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batches', sa.Column('num_learners', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_batches_name'), table_name='batches')
    op.alter_column('batches', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('batches', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('batches', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('batch_students', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('batch_faculties', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_table('test_student')
    op.drop_table('test_faculty')
    op.drop_table('course_subject')
    op.drop_table('course_student')
    op.drop_table('course_faculty')
    op.drop_index(op.f('ix_course_contents_id'), table_name='course_contents')
    op.drop_table('course_contents')
    op.drop_table('course_batch')
    op.drop_index(op.f('ix_tests_test_name'), table_name='tests')
    op.drop_index(op.f('ix_tests_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
